(() => {
'use strict';
const canvas=document.getElementById('canvas'), ctx=canvas.getContext('2d');
const wrap=document.getElementById('canvasWrap');
const state={tool:'select',color:'#222222',size:8,zoom:1,objects:[],selected:null,history:[],future:[],drawing:null,drag:null,shape:'rect'};
const $=id=>document.getElementById(id);
function resize(){const r=wrap.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);draw()}window.addEventListener('resize',resize);resize();
function snap(){state.history.push(JSON.stringify(state.objects));if(state.history.length>40)state.history.shift();state.future=[]}
function restore(s){state.objects=JSON.parse(s);state.selected=null;draw()}
function undo(){if(!state.history.length)return;state.future.push(JSON.stringify(state.objects));restore(state.history.pop())}
function redo(){if(!state.future.length)return;state.history.push(JSON.stringify(state.objects));restore(state.future.pop())}
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/state.zoom,y:(e.clientY-r.top)/state.zoom}}
function draw(){const r=wrap.getBoundingClientRect();ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#fffdf8';ctx.fillRect(0,0,r.width,r.height);ctx.restore();ctx.save();ctx.scale(state.zoom,state.zoom);for(const o of state.objects)drawObj(o);if(state.selected!==null){const o=state.objects[state.selected];if(o)drawSelection(o)}ctx.restore();$('emptyHint').classList.toggle('hidden',state.objects.length>0);$('selectionInfo').textContent=state.selected===null?'Nic nevybráno':`Objekt ${state.selected+1}`}
function drawObj(o){ctx.save();ctx.globalAlpha=o.opacity??1;ctx.strokeStyle=o.color||'#222';ctx.fillStyle=o.fill||'transparent';ctx.lineWidth=o.size||3;ctx.lineCap='round';ctx.lineJoin='round';if(o.type==='path'){ctx.beginPath();o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else{const x=o.x,y=o.y,w=o.w,h=o.h;if(o.type==='rect'){o.fill&&ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h)}if(o.type==='circle'){ctx.beginPath();ctx.ellipse(x+w/2,y+h/2,Math.abs(w/2),Math.abs(h/2),0,0,Math.PI*2);o.fill&&ctx.fill();ctx.stroke()}if(o.type==='triangle'){ctx.beginPath();ctx.moveTo(x+w/2,y);ctx.lineTo(x+w,y+h);ctx.lineTo(x,y+h);ctx.closePath();o.fill&&ctx.fill();ctx.stroke()}if(o.type==='line'){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+w,y+h);ctx.stroke()}if(o.type==='star'){star(ctx,x+w/2,y+h/2,Math.min(Math.abs(w),Math.abs(h))/2,Math.min(Math.abs(w),Math.abs(h))/4,5);o.fill&&ctx.fill();ctx.stroke()}if(o.type==='text'){ctx.font=`${o.size||32}px system-ui`;ctx.fillStyle=o.color||'#222';ctx.fillText(o.text||'Text',x,y+h)}}ctx.restore()}
function star(c,cx,cy,r,ir,n){c.beginPath();for(let i=0;i<n*2;i++){const a=-Math.PI/2+i*Math.PI/n,rr=i%2?r:ir;c.lineTo(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr)}c.closePath()}
function bounds(o){if(o.type==='path'){let xs=o.points.map(p=>p.x),ys=o.points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}return{x:o.x,y:o.y,w:o.w,h:o.h}}
function hit(o,p){const b=bounds(o),pad=10/state.zoom;return p.x>=b.x-pad&&p.x<=b.x+b.w+pad&&p.y>=b.y-pad&&p.y<=b.y+b.h+pad}
function drawSelection(o){const b=bounds(o);ctx.save();ctx.strokeStyle='#1f1f1f';ctx.setLineDash([5,4]);ctx.lineWidth=1/state.zoom;ctx.strokeRect(b.x-5,b.y-5,b.w+10,b.h+10);ctx.setLineDash([]);const pts=[[b.x,b.y],[b.x+b.w/2,b.y],[b.x+b.w,b.y],[b.x+b.w,b.y+b.h/2],[b.x+b.w,b.y+b.h],[b.x+b.w/2,b.y+b.h],[b.x,b.y+b.h],[b.x,b.y+b.h/2]];ctx.fillStyle='#fff';ctx.strokeStyle='#111';for(const p of pts){ctx.beginPath();ctx.arc(p[0],p[1],5/state.zoom,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
function selectAt(p){for(let i=state.objects.length-1;i>=0;i--)if(hit(state.objects[i],p)){state.selected=i;updateProps();draw();return}state.selected=null;updateProps();draw()}
function addShape(type,x,y,w,h){snap();state.objects.push({type,x,y,w,h,color:state.color,fill:'transparent',size:3,opacity:1});state.selected=state.objects.length-1;updateProps();draw()}
function pointerDown(e){const p=pos(e);if(state.tool==='select'){selectAt(p);if(state.selected!==null){state.drag={start:p,before:JSON.stringify(state.objects[state.selected]),mode:'move'}}}else if(state.tool==='brush'||state.tool==='eraser'){state.drawing={type:'path',points:[p],color:state.tool==='eraser'?'#fffdf8':state.color,size:state.size,opacity:1};state.objects.push(state.drawing)}else if(state.tool==='shape'){addShape(state.shape,p.x,p.y,1,1);state.drag={start:p,before:JSON.stringify(state.objects[state.selected]),mode:'resize'}}canvas.setPointerCapture?.(e.pointerId)}
function pointerMove(e){const p=pos(e);if(state.drawing){state.drawing.points.push(p);draw();return}if(!state.drag)return;const o=state.objects[state.selected];if(!o)return;const d={x:p.x-state.drag.start.x,y:p.y-state.drag.start.y};if(state.drag.mode==='move'){o.x+=d.x;o.y+=d.y;state.drag.start=p}else{o.w=d.x;o.h=d.y}draw()}
function pointerUp(){if(state.drawing){snap();state.drawing=null;draw()}if(state.drag){if(state.drag.mode==='move'||state.drag.mode==='resize')snap();state.drag=null}}
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);
canvas.addEventListener('contextmenu',e=>{e.preventDefault();selectAt(pos(e))});
function setTool(t){state.tool=t;$('[data-tool="'+t+'"]')?.classList.add('active');document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('modeLabel').textContent={select:'Výběr',brush:'Štětec',eraser:'Guma',eyedropper:'Kapátko',shape:'Tvary',text:'Text',layers:'Vrstvy'}[t]||t}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{setTool(b.dataset.tool);if(b.dataset.tool==='shape')$('shapePopover').classList.toggle('hidden')});document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>{state.shape=b.dataset.shape;setTool('shape');$('shapePopover').classList.add('hidden')});
$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('zoomIn').onclick=()=>{state.zoom=Math.min(3,state.zoom+.1);$('zoomLabel').textContent=Math.round(state.zoom*100)+'%';draw()};$('zoomOut').onclick=()=>{state.zoom=Math.max(.4,state.zoom-.1);$('zoomLabel').textContent=Math.round(state.zoom*100)+'%';draw()};$('fitBtn').onclick=()=>{state.zoom=1;$('zoomLabel').textContent='100%';draw()};
function open(id){$(id).classList.remove('hidden')}function close(id){$(id).classList.add('hidden')}
$('menuBtn').onclick=()=>open('menuModal');$('closeMenu').onclick=()=>close('menuModal');$('closeAd').onclick=()=>close('adModal');$('close3d').onclick=()=>close('threeModal');$('closePalette').onclick=()=>close('paletteModal');$('settingsBtn').onclick=()=>open('paletteModal');$('colorBtn').onclick=()=>open('paletteModal');
let pending=null;document.querySelectorAll('.menu-item').forEach(b=>b.onclick=()=>{pending=b.dataset.action;close('menuModal');open('adModal')});$('continueAd').onclick=()=>{close('adModal');if(pending==='new'){snap();state.objects=[];state.selected=null;draw()}else if(pending==='3d')open3D();else if(pending==='convert')convert2Dto3D()};
function updateProps(){const root=$('propertyContent');if(state.selected===null){root.innerHTML='<p class="muted">Vyber objekt.</p>';return}const o=state.objects[state.selected],b=bounds(o);root.innerHTML=`<div class="prop"><label>Typ</label><strong>${o.type}</strong></div><div class="prop"><label>Barva</label><input id="pcolor" type="color" value="${o.color||'#222222'}"></div><div class="prop"><label>Průhlednost</label><input id="popacity" type="range" min="0" max="1" step=".01" value="${o.opacity??1}"></div><div class="prop"><label>Šířka</label><input id="pw" type="number" value="${Math.round(b.w)}"></div><div class="prop"><label>Výška</label><input id="ph" type="number" value="${Math.round(b.h)}"></div><div class="prop"><button class="primary" id="deleteObj">Smazat objekt</button></div>`;$('pcolor').oninput=e=>{o.color=e.target.value;draw()};$('popacity').oninput=e=>{o.opacity=+e.target.value;draw()};$('pw').onchange=e=>{if(o.w!==undefined)o.w=Math.max(1,+e.target.value);draw()};$('ph').onchange=e=>{if(o.h!==undefined)o.h=Math.max(1,+e.target.value);draw()};$('deleteObj').onclick=()=>{snap();state.objects.splice(state.selected,1);state.selected=null;updateProps();draw()}}
$('closeProperties').onclick=()=>$('properties').classList.remove('open');$('layersBtn').onclick=()=>{$('properties').classList.add('open');updateProps()};
const palettes=[['#f5f1e8','#252525','#a66a4c','#65745b'],['#fff8ed','#292522','#d95f59','#e8a83e','#5d8c72'],['#181818','#f2eee6','#d7a85b','#c96b5b'],['#faf7f0','#222222','#e85d5d','#f2b84b','#67a978','#5794c4']];$('palettes').innerHTML=palettes.map((p,i)=>`<div class="palette-row">${p.map(c=>`<button class="sw" style="background:${c}" data-palette="${i}" data-color="${c}" aria-label="${c}"></button>`).join('')}<button data-choose="${i}">Zvolit</button></div>`).join('');document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>{const p=palettes[+b.dataset.choose];document.documentElement.style.setProperty('--panel',p[0]);document.documentElement.style.setProperty('--text',p[1]);state.color=p[1];$('colorBtn').style.background=state.color;close('paletteModal')});$('customColor').oninput=e=>{state.color=e.target.value;$('colorBtn').style.background=state.color};
function exportPNG(){const link=document.createElement('a');link.download='drawcraft.png';link.href=canvas.toDataURL('image/png');link.click()}
document.querySelector('[data-action="export"]').onclick=()=>{close('menuModal');exportPNG()};document.querySelector('[data-action="palette"]').onclick=()=>{close('menuModal');open('paletteModal')};
function open3D(){open('threeModal');init3D()}
let threeReady=false,tc,tctx,cam={rx:-.5,ry:.7,zoom:1},primitive='cube',drag3=null;
function init3D(){if(threeReady)return;tc=$('threeCanvas');tctx=tc.getContext('2d');threeReady=true;resize3();window.addEventListener('resize',resize3);tc.addEventListener('pointerdown',e=>{drag3={x:e.clientX,y:e.clientY}});tc.addEventListener('pointermove',e=>{if(!drag3)return;cam.ry+=(e.clientX-drag3.x)*.01;cam.rx+=(e.clientY-drag3.y)*.01;drag3={x:e.clientX,y:e.clientY};draw3()});tc.addEventListener('pointerup',()=>drag3=null);tc.addEventListener('wheel',e=>{e.preventDefault();cam.zoom=Math.max(.5,Math.min(2,cam.zoom-e.deltaY*.001));draw3()},{passive:false});draw3()}
function resize3(){if(!tc)return;const r=tc.getBoundingClientRect(),d=devicePixelRatio||1;tc.width=r.width*d;tc.height=r.height*d;tctx.setTransform(d,0,0,d,0,0);draw3()}
function project(v){const [x,y,z]=v,cy=Math.cos(cam.ry),sy=Math.sin(cam.ry),cx=Math.cos(cam.rx),sx=Math.sin(cam.rx);let X=x*cy-z*sy,Z=x*sy+z*cy,Y=y*cx-Z*sx;Z=y*sx+Z*cx;const s=130*cam.zoom/(4-Z);return [tc.clientWidth/2+X*s,tc.clientHeight/2-Y*s]}
function cubeVerts(kind){let x=kind==='sphere'?1:kind==='cuboid'?1.4:1,y=kind==='cuboid'?1:1,z=kind==='cuboid'?.7:1;return[[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]]}
function draw3(){if(!tctx)return;const r=tc.getBoundingClientRect();tctx.fillStyle='#252525';tctx.fillRect(0,0,r.width,r.height);const vs=cubeVerts(primitive),pts=vs.map(project);const edges=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];tctx.strokeStyle='#f2eee6';tctx.lineWidth=2;for(const e of edges){tctx.beginPath();tctx.moveTo(...pts[e[0]]);tctx.lineTo(...pts[e[1]]);tctx.stroke()}if(primitive==='sphere'){tctx.strokeStyle='#aaa';tctx.beginPath();tctx.ellipse(r.width/2,r.height/2,120*cam.zoom,120*cam.zoom,0,0,Math.PI*2);tctx.stroke()}$('threeStatus').textContent=`Objekt: ${primitive} · přetáhni pro otočení`}
document.querySelectorAll('[data-primitive]').forEach(b=>b.onclick=()=>{primitive=b.dataset.primitive;draw3()});
function convert2Dto3D(){let o=state.selected!==null?state.objects[state.selected]:state.objects[state.objects.length-1];if(!o){alert('Nejdřív něco nakresli nebo označ objekt.');return}open3D();setTimeout(()=>{$('threeStatus').textContent=`Převedeno z 2D objektu „${o.type}“ · upravuj náhled 3D`},0)}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}if(e.key==='Escape'){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'))}});
$('colorBtn').style.background=state.color;setTool('select');
})();
